CREATE TABLE produtos
(
    pro_pk INT NOT NULL PRIMARY KEY,
    pro_fk_grupo INT,
    pro_fk_subgrupo INT,
    pro_b_ativo VARCHAR(1) DEFAULT 'T',
    pro_b_balanca VARCHAR(1) DEFAULT 'F',
    pro_b_destaque VARCHAR(1) DEFAULT 'F',
    pro_b_estoque VARCHAR(1) DEFAULT 'F',
    pro_b_favorito VARCHAR(1) DEFAULT 'F',
    pro_b_fracionado VARCHAR(1) DEFAULT 'F',
    pro_b_industrializado VARCHAR(1) DEFAULT 'T',
    pro_c_barcode CHAR(20) DEFAULT NULL,
    pro_c_descricao CHAR(60) DEFAULT NULL,
    pro_c_img CHAR(60) DEFAULT NULL,
    pro_c_fracionado_tipo CHAR(5) DEFAULT NULL,
    pro_c_produto CHAR(60) DEFAULT NULL,
    pro_f_perc_limite_venda DECIMAL(10,2) DEFAULT 0.00,
    pro_f_fracionado_fracao DECIMAL(10,2) DEFAULT 0.00,
    pro_f_preco DECIMAL(10,2) DEFAULT 0.00,
    pro_f_qtde_atacado DECIMAL(10,2) DEFAULT 0.00,
    pro_f_qtde_estoque_loja DECIMAL(10,2) DEFAULT 0.00,
    pro_f_qtde_estoque_min DECIMAL(10,2) DEFAULT 0.00,
    pro_f_qtde_limite_venda DECIMAL(10,2) DEFAULT 0.00,
    pro_f_valor_atacado DECIMAL(10,2) DEFAULT 0.00,
    pro_i_cod INT DEFAULT NULL
);

INSERT INTO PRODUTOS (PRO_PK, PRO_FK_GRUPO, PRO_FK_SUBGRUPO, PRO_B_ATIVO,
    PRO_B_BALANCA, PRO_B_DESTAQUE, PRO_B_ESTOQUE, PRO_B_FAVORITO,
    PRO_B_FRACIONADO, PRO_B_INDUSTRIALIZADO, PRO_C_BARCODE, PRO_C_DESCRICAO,
    PRO_C_IMG, PRO_C_FRACIONADO_TIPO, PRO_C_PRODUTO, PRO_F_PERC_LIMITE_VENDA,
    PRO_F_FRACIONADO_FRACAO, PRO_F_PRECO, PRO_F_QTDE_ATACADO,
    PRO_F_QTDE_ESTOQUE_LOJA, PRO_F_QTDE_ESTOQUE_MIN, PRO_F_QTDE_LIMITE_VENDA,
    PRO_F_VALOR_ATACADO, PRO_I_COD)
VALUES (
    416, 
    1, 
    0, 
    'T', 
    'F', 
    'F', 
    'F', 
    'F', 
    'F', 
    'T', 
    '7896020417149', 
    '', 
    '', 
    '', 
    'THREE BOND 2G TRADICIONAL', 
    0, 
    0, 
    2.0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0
);

INSERT INTO PRODUTOS (PRO_PK, PRO_FK_GRUPO, PRO_FK_SUBGRUPO, PRO_B_ATIVO,
    PRO_B_BALANCA, PRO_B_DESTAQUE, PRO_B_ESTOQUE, PRO_B_FAVORITO,
    PRO_B_FRACIONADO, PRO_B_INDUSTRIALIZADO, PRO_C_BARCODE, PRO_C_DESCRICAO,
    PRO_C_IMG, PRO_C_FRACIONADO_TIPO, PRO_C_PRODUTO, PRO_F_PERC_LIMITE_VENDA,
    PRO_F_FRACIONADO_FRACAO, PRO_F_PRECO, PRO_F_QTDE_ATACADO,
    PRO_F_QTDE_ESTOQUE_LOJA, PRO_F_QTDE_ESTOQUE_MIN, PRO_F_QTDE_LIMITE_VENDA,
    PRO_F_VALOR_ATACADO, PRO_I_COD)
VALUES (
    1004, 
    1, 
    0, 
    'T', 
    'F', 
    'F', 
    'F', 
    'F', 
    'F', 
    'T', 
    '7896020417149', 
    '', 
    '', 
    '', 
    'VONO SOPA MILHO C/FRANGO 15G', 
    0, 
    0, 
    2.25, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0
);